### ISSUE TITLE
Add pagination and meta

### ISSUE THREAD

**Issue by YaroShkvorets** [pinax-network/antelope-token-api#1]
In our Go services we have somewhat of a standard to use `limit` and `page` query parameters to paginate, and have `data`  and `meta` fields in the response to help with pagination:
```
{
  "data": [
...
],
  "meta": {
    "next_page": 3,
    "prev_page": 1,
    "total_pages": 4,
    "total_docs": 4
  }
}
```

Would be nice to have the same schema here. In addition, `meta` can contain current head block and/or timestamp to know how far behind is syncing.

Example: https://api.dev.pomelo.io/v1/bounties?limit=1&page=2

**Comment by 0237h** [comment]
@YaroShkvorets Pagination should be working properly now !

As for adding other information in `meta` response, I would suggest having a separate issue to track this.
