### ISSUE TITLE
Add a /version endpoint

### ISSUE THREAD

**Issue by fschoell** [pinax-network/antelope-token-api#13]
It would be good to have a `/version` endpoint that exposes the API's deployed version (if tagged, otherwise something static like `dev`) and the commit hash. That makes it easy to see what version is deployed when visiting the API. See this endpoint on the Pinax Accout API for example: https://api.account.pinax.network/swagger/index.html#/version/get_version

**Comment by 0237h** [comment]
Thanks for the feature request !

I agree, should be useful to have an endpoint for this. I actually implemented it for the logging already in #10. Just need to add tags potentially as well.

I will look into it 👍🏻
