### ISSUE TITLE
Add more information in the`meta` object of the API reponse

### ISSUE THREAD

**Issue by 0237h** [pinax-network/antelope-token-api#8]
## Detailed Description

The `meta` field in the response can be used to hold additional useful information related to the API's back-end status. It could also hold more information about the query itself like response time, etc.

## Context

#3 added the pagination information as a `meta` object in the response. @YaroShkvorets in #1 also suggested to add other information to it:
>  In addition, meta can contain current head block and/or timestamp to know how far behind is syncing. 

## Possible Implementation

- ClickHouse returns [additional information](https://clickhouse.com/docs/en/interfaces/formats#jsoncolumnsmonoblock) that is currently [only used](https://github.com/pinax-network/antelope-token-api/blob/main/src/clickhouse/makeQuery.ts#L9-L32) for the `/metrics` endpoint. Those could also be returned in the `meta` field. 
- For details on the syncing status, we would need to craft a new ClickHouse query for the latest block height and/or other relevant information. Ideally, the syncing details should be `sink` agnostic and ClickHouse should hold all the necessary data.

## Other alternatives

This information could also be returned from a new endpoint depending on the use case.

**Comment by 0237h** [comment]
@YaroShkvorets I'm actually more in line with adding another endpoint for that type of information. Do you think it should be available also in the `meta` field ? Or would having a separate endpoint be enough ?

**Comment by YaroShkvorets** [comment]
> For details on the syncing status, we would need to craft a new ClickHouse query for the latest block height and/or other relevant information. Ideally, the syncing details should be sink agnostic and ClickHouse should hold all the necessary data.

On a second thought, we probably shouldn't execute a separate "get head block number" query with every request. It probably just needs its own endpoint like `/health`

> ClickHouse returns [additional information](https://clickhouse.com/docs/en/interfaces/formats#jsoncolumnsmonoblock) that is currently [only used](https://github.com/pinax-network/antelope-token-api/blob/main/src/clickhouse/makeQuery.ts#L9-L32) for the /metrics endpoint. Those could also be returned in the meta field.

These metrics returned by ClickHouse could be pretty useful for troubleshooting:
```
                "elapsed": 0.000272376,
                "rows_read": 3,
                "bytes_read": 24
```
Also we could return the entire executed SQL query.
Although that's probably not something we should return these with every request. Maybe to our team members only based on `x-api-key`?

**Comment by 0237h** [comment]
> On a second thought, we probably shouldn't execute a separate "get head block number" query with every request. It probably just needs its own endpoint like `/health`

Agreed, something like `/head` that would provide that information.
 
> These metrics returned by ClickHouse could be pretty useful for troubleshooting:
> 
> ```
>                 "elapsed": 0.000272376,
>                 "rows_read": 3,
>                 "bytes_read": 24
> ```
 
Definitely, will work on adding that to the `meta` field as well.

> Also we could return the entire executed SQL query. Although that's probably not something we should return these with every request. Maybe to our team members only based on `x-api-key`?

The logger actually already outputs the executed query ([code](https://github.com/pinax-network/antelope-token-api/blob/main/src/clickhouse/makeQuery.ts#L30)). I assume you would want that information for monitoring purposes ? In that case I think having the logs is probably just fine.
